name: flutter_france_identite
description: A flutter package helping with linking the France Identite service with flutter applications.
version: 2.1.2
repository: https://github.com/eljanvier2/Flutter-France-Identite.git

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  external_app_launcher: ^3.1.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_sharing_intent: ^1.1.0
  flutter_svg: ^2.0.9
  http: ^0.13.5
  http_parser: ^4.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo_france_identite.svg
    - assets/logo_marianne.svg
