name: flutter_france_identite
description: A flutter package helping with linking the France Identite service with flutter applications.
version: 0.0.1

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  external_app_launcher: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo_france_identite.svg
    - assets/logo_marianne.svg